#this removes obj and exe file generated by vcvarsall x64 // cl commands just to clean the repo while pushing into github

#general imports
import os
import sys
import re


#set path
#root_path = "C:\Users\User.FULL272-WIN.000\AppData\Local\Google\Chrome\User Data\Default\Cache"

root_path = "C:/Users/User.FULL272-WIN.000/Desktop/experiment"

#get total list of files available in directory

listofTotalFiles=os.listdir(root_path)
print("All the Available files in directory:\n "+ str(listofTotalFiles))

#filter only the files to be removed

#create regex
regex= "f_[\w]*"
for i in range(3,len(sys.argv)):
       regex += ("|" + sys.argv[i]) 
print("regex=" + regex)

#get the removing files list

fileTypeRegex = re.compile(regex)
removingList = list(filter(fileTypeRegex.search, listofTotalFiles)) # Read Note
print("the following list of files will be removed =" + str(removingList) + "\n Continue ? Y/N")

# ask the user whether to delete the files shown
deleteFlag = input()
if deleteFlag.lower().__contains__('n'):
    print("\nteriminating the process")
    sys.exit(1)


#remove the files

for File in removingList:
    try:
        os.remove(os.path.join(root_path,str(File)))
        print("file removed: " + str(File))
    except OSError as e:  ## if failed, report it back to the user ##
        print ("Error: %s - %s." % (e.filename, e.strerror))

print("\n Deleted the files")